### ISSUE TITLE
PHP Loop

### ISSUE THREAD

**Issue by manoelfranklin** [andrewscofield/parse.com-php-library#14]
Hello guys! I'm doing something like this... A loop to trigger notifications.

This loop is supposed to run 10 times, but at the first time it reaches:

$request = $parse->notification($params);

It stops. The loop stops. How to fix it? Thank you!

Sample Code:

while($row = mysql_fetch_array($query)) {
....
            $data = array(
                'alert' => $message,
                'badge' => '1',
                'sound' => 'default'
            );

```
        $params = array(
            'channel' => $row1['tus_usuar'],
            'type' => 'ios',
            'data' => $data
        );

        $request = $parse->notification($params);
        $sql2 = "UPDATE tab_comentarios SET fl_notif = '1' WHERE id = '$id'";
        $query2 = mysql_query($sql2, $conexao);

    }
}
```

**Comment by manoelfranklin** [comment]
The loop stops on the 1st run and do not execute any line after $request = $parse->notification($params);.

I need to send different messages to different users, so I really need a loop like this.

Any ideas?

**Comment by andrewscofield** [comment]
Hey, I'm working on a new version of the library that will help you out a lot! Notification will be easier to better supported. 

That said, I think the problem you are having is that it is having an error on return, you just aren't seeing it for some reason. The most common error when trying a notification is because your parse account isn't setup for push notifications yet. Check out your account under 'Settings' -> 'Push Notifications' and make sure you have everything setup correctly there.

**Comment by andrewscofield** [comment]
New version is available here as a beta: https://github.com/apotropaic/parse.com-php-library/tree/2.0/master
