### ISSUE TITLE
Get currentUser

### ISSUE THREAD

**Issue by iantearle** [andrewscofield/parse.com-php-library#7]
Is there a way to get the current logged in user with this library?

See http://www.parse.com/docs/ios/api/Classes/PFUser.html#//api/name/currentUser

**Comment by andrewscofield** [comment]
Kind of... here is the api methods available in php: https://www.parse.com/docs/rest#users

I say kind of, because if you login a user in via the REST api, it will return their 'sessionToken'. 'currentUser' wouldn't really make sense when making calls via rest, its used to identify the person using the mobile device. The REST api is typically used so a server can add/update/delete data on parse for users, so when they do login, latest data is already there. 

But another method is if a user opens your mobile app and makes a call to your php server, you could in theory identify them using a token that when checked against your servers database would point to the 'current user'. This article here, sort of touches on this subject and is a good read:

http://www.thebuzzmedia.com/designing-a-secure-rest-api-without-oauth-authentication/

Not sure if this is your particular use case, let me know if you still have questions though.

**Comment by iantearle** [comment]
Thank you, that's great.
However bumped into a query, might be just me being stupid late on a monday afternoon, but can one login using this library? I tried using the GET method but its requiring an objectid?

**Comment by andrewscofield** [comment]
I'm working on that, it will be possible soon.

**Comment by iantearle** [comment]
phew. I thought for a minute I was going mad. I'll hang tight. Thanks.

**Comment by ghost** [comment]
Hi, I'm having similar issues, I just want to get the details of one user with this library - I have tried with multiple user objectIds, I get a 404 error even though the id is perfectly valid.

**Comment by andrewscofield** [comment]
Can you please show me a small code sample that is not working for you. Also can you tell me if other functions of the library are working?

**Comment by ghost** [comment]
Here's the code:

```
    $user = array(
        'className' => 'User',
        'objectId' => $userId
    );
    // fetch user info.
    $json = json_decode($parse->get($user), true);
    print_r($json);
```

Anything other than user objects, the library works fine and returns the correct data.

**Comment by andrewscofield** [comment]
A couple things are off there. It looks like you are using the provided parseUser class. Try something like this instead:

```
//you first have to setup a new parse user instance
//then you can make all the user functions like get and query and signup. 
$user = new parseUser;
$userData = $user->get($userId); 
print_r($userData);

//Also no need to json_decode any of the stuff this library returns. Already done in the library. 
```

Check out this file here for more examples:
https://github.com/apotropaic/parse.com-php-library/blob/master/tests/parseUserTest.php

**Comment by ghost** [comment]
Ah, I'm still using v1 of the library, is this fix for the new one?

**Comment by andrewscofield** [comment]
yea it is.

**Comment by ghost** [comment]
Ok, here's my code for retrieving a user object:

```
        $parseQuery = new parseQuery('User');
        $parseQuery->where('objectId',$args[1]);
        $result = $parseQuery->find();
        print_r($result);
```

I still get an empty response though, even though the table is populated:

```
        stdClass Object ( [results] => Array ( ) ) 
```

I have constructed queries to other tables and they do work.

**Comment by ghost** [comment]
Ah, problem solved, I forgot to run your first solution as the new query. Works perfectly now, thanks.

**Comment by andrewscofield** [comment]
Sweet! Glad to hear man.. just open up a new issue if you have any other
questions or suggestions.
